name: tmate-parallel-sessions

on:
  workflow_dispatch:

jobs:
  tmate-session:
    runs-on: ubuntu-latest
    timeout-minutes: 61
    strategy:
      matrix:
        job_id: [1, 2, 3, 4, 5]
    steps:
      - name: Install tmate
        run: |
          sudo apt-get update
          sudo apt-get install -y tmate

      - name: Start tmate session
        run: |
          tmate -S /tmp/tmate.sock new-session -d
          tmate -S /tmp/tmate.sock wait tmate-ready
          echo "Web URL:"
          tmate -S /tmp/tmate.sock display -p 'https://web.tmate.io/tmate/${tmate_ssh}'
          echo "SSH URL:"
          tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}'
          echo "Session will be kept alive for 1 hour."
          sleep 3600

      - name: Print tmate web session URL
        run: |
          echo "Connect to your session using the web URL below:"
          tmate -S /tmp/tmate.sock display -p 'https://web.tmate.io/tmate/${tmate_ssh}'
