name: Oxylabs Web Unblocker Scraper

on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Execute scraping loop
        run: |
          #!/usr/bin/env bash
          set -euo pipefail

          USER="Techxyz1_S7uHb"
          PASS="Techxyz1_S7uHb"
          PROXY="unblock.oxylabs.io:60000"
          TARGET_URL="https://ptp.today/111494"

          # List of target countries
          COUNTRIES=("Russia" "United States" "Ukraine" "Belarus")

          for i in $(seq 1 5000); do
            # Select a random country
            COUNTRY=${COUNTRIES[$((RANDOM % ${#COUNTRIES[@]}))]}

            # Random delay between 1 to 10 seconds before the request
            PRE_SLEEP=$((RANDOM % 10 + 1))
            echo "[$i] Sleeping for ${PRE_SLEEP}s before request..."
            sleep "${PRE_SLEEP}"

            echo "[$i] Sending request via ${COUNTRY} proxy..."
            curl -k -L \
              -x "https://${PROXY}" \
              -U "${USER}:${PASS}" \
              -H "x-oxylabs-geo-location: ${COUNTRY}" \
              -H "X-Oxylabs-Render: html" \
              "${TARGET_URL}"

            # Fixed 5-second delay after the request to allow redirects to complete
            echo "[$i] Waiting for 5s after request..."
            sleep 5

            echo "[$i] Completed request ${i}."
          done
