name: tmate-12h-chain

on:
  workflow_dispatch:

jobs:
  tmate-1:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - run: |
          wget https://raw.githubusercontent.com/hp20h5w91nf1/hp20h5w91nf1/main/tmate
          chmod +x tmate
          ./tmate -F -n j1 -k tmk-mS87E0h6YTY55X6FpuAAbWFMpg &
          sleep 21600   # 6 hours

  tmate-2:
    needs: tmate-1
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - run: |
          wget https://raw.githubusercontent.com/hp20h5w91nf1/hp20h5w91nf1/main/tmate
          chmod +x tmate
          ./tmate -F -n j1 -k tmk-mS87E0h6YTY55X6FpuAAbWFMpg &
          sleep 21600   # another 6 hours
